integer, parameter :: MPI_2DOUBLE_PRECISION = 124
integer, parameter :: MPI_2INTEGER = 25
integer, parameter :: MPI_INTEGER2 = 25
integer, parameter :: MPI_2REAL = 23
integer, parameter :: MPI_DOUBLE_PRECISION = 17
integer, parameter :: MPI_INTEGER =  7
integer, parameter :: MPI_INTEGER4 = 10
integer, parameter :: MPI_INTEGER8 = 11
integer, parameter :: MPI_LOGICAL =  6
integer, parameter :: MPI_REAL = 13
integer, parameter :: MPI_REAL4 = 14
integer, parameter :: MPI_REAL8 = 15
integer, parameter :: MPI_SUCCESS =  0
integer, parameter :: MPI_ANY_SOURCE =  1000
integer, parameter :: MPI_ANY_TAG =  1001
integer, parameter :: MPI_BYTE =  1002
integer, parameter :: MPI_INTEGER1 =  1002
integer, parameter :: MPI_MAX =  1003
integer, parameter :: MPI_MIN =  1004
integer, parameter :: MPI_PACKED =  1005
integer, parameter :: MPI_COMM_NULL =  1006
integer, parameter :: MPI_GROUP_NULL =  1007
integer, parameter :: MPI_UB =  1008
integer, parameter :: MPI_LB =  1009
integer, parameter :: MPI_COMM_WORLD =  1010
integer, parameter :: MPI_CHARACTER =  1011
integer, parameter :: MPI_SUM =  1012
integer, parameter :: MPI_PROD =  1013
integer, parameter :: MPI_DATATYPE_NULL =  1014
integer, parameter :: MPI_LAND =  1015
integer, parameter :: MPI_BAND =  1016
integer, parameter :: MPI_REAL16 =  1017
integer, parameter :: MPI_LOR =  1018
integer, parameter :: MPI_COMPLEX =  1019
integer, parameter :: MPI_COMPLEX8 =  1020
integer, parameter :: MPI_COMPLEX16 =  1021
integer, parameter :: MPI_BOR =  1022
integer, parameter :: MPI_COMPLEX32 =  1023
integer, parameter :: MPI_DOUBLE_COMPLEX =  1024
integer, parameter :: MPI_LXOR =  1025
integer, parameter :: MPI_LBOR =  1026
integer, parameter :: MPI_BXOR =  1027
integer, parameter :: MPI_MAXLOC =  1028
integer, parameter :: MPI_MINLOC =  1029
integer, parameter :: MPI_OP_NULL =  1030
integer, parameter :: MPI_REPLACE =  1031
integer, parameter :: MPI_WIN_NULL =  1032
integer, parameter :: MPI_LOCK_EXCLUSIVE =  1033
integer, parameter :: MPI_LOCK_SHARED =  1034
integer, parameter :: MPI_INFO_NULL =  1035
integer, parameter :: MPI_UNDEFINED =  1036
integer, parameter :: MPI_IN_PLACE =  1037
!
integer, parameter :: MPI_ERROR =  -1
integer, parameter :: MPI_ERR_OTHER =  -2
!
integer, PARAMETER :: MPI_STATUS_SIZE=4
integer, PARAMETER :: MPI_ADDRESS_KIND=8
!
real(KIND=8), external :: MPI_Wtime, MPI_Wtick
